### ISSUE TITLE
Exception with prefix *

### ISSUE THREAD

**Issue by danthe1st** [danthe1st/DanBot1#3]
An Exception occurs, whenever a Command with the prefix _*_ is executed (prefix can be set with the Command `prefix set`

Stacktrace:
`java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0^M
*^M
^^M
        at java.util.regex.Pattern.error(Pattern.java:1955)^M
        at java.util.regex.Pattern.sequence(Pattern.java:2123)^M
        at java.util.regex.Pattern.expr(Pattern.java:1996)^M
        at java.util.regex.Pattern.compile(Pattern.java:1696)^M
        at java.util.regex.Pattern.<init>(Pattern.java:1351)^M
        at java.util.regex.Pattern.compile(Pattern.java:1028)^M
        at java.lang.String.replaceFirst(String.java:2178)^M
        at io.github.danthe1st.danbot1.core.CommandParser.parser(CommandParser.java:33)^M
        at io.github.danthe1st.danbot1.core.CommandParser.parser(CommandParser.java:22)^M
        at io.github.danthe1st.danbot1.listeners.CommandListener.onMessageReceived(CommandListener.java:37)^M
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:336)^M
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)^M
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:118)^M
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37)^M
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:860)^M
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:758)^M
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:737)^M
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:895)^M
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)^M
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)^M
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)^M
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)^M
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)^M
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)^M
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)^M
`

**Comment by danthe1st** [comment]
fixed with commit 0800fa390ab9af842174676e85ac63809ec5abf1

**Comment by danthe1st** [comment]
not fixed with 0800fa3 but with 3a758df3f53eacfa1fdd07fa33061a98213d6b5c
